---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name zfs-generic-iscsi-config
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: zfs-generic-iscsi
          sshConnection:
            host: 10.33.100.1
            port: 22
            username: admin
            privateKey: |
              {{ .SSH_PRIVATE_KEY }}
          zfs:
            cli:
              sudoEnabled: true
            datasetParentName: test/k8s/test
            detachedSnapshotsDatasetParentName: test/k8s/test-snapshots
          iscsi:
            shareStrategy: "targetCli"
            shareStrategyTargetCli:
              sudoEnabled: true
              basename: "iqn.1993-08.org.debian:01:e7ee99cbcaa"
            namePrefix: "csi-"
            nameSuffix: "-cluster"

  dataFrom:
  - extract:
      key: /democratic-csi
