---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app glauth
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: glauth
  values:
    externalSecrets:
      main:
        secretStoreRef:
          name: akeyless-secret-store
          kind: ClusterSecretStore
        target:
          name: glauth-secret
          template:
            engineVersion: v2
            # Create passbcrypt:
            #   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
            # or
            #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
            data:
              server.toml: |
                debug = true
                [api]
                  enabled = true
                  tls = false
                  listen = "0.0.0.0:5555"
                [ldap]
                  enabled = true
                  listen = "0.0.0.0:389"
                [ldaps]
                  enabled = false
                [backend]
                  datastore = "config"
                  baseDN = "dc=home,dc=arpa"
                  anonymousdse = true
              groups.toml: |
                [[groups]]
                  name = "svcaccts"
                  gidnumber = 6500
                [[groups]]
                  name = "admins"
                  gidnumber = 6501
                [[groups]]
                  name = "people"
                  gidnumber = 6502
              users.toml: |
                [[users]]
                  name = "search"
                  uidnumber = 5000
                  primarygroup = 6500
                  passbcrypt = "{{ .GLAUTH_SEARCH_PASSWORD_BCRYPT }}"
                  [[users.capabilities]]
                    action = "search"
                    object = "*"
                [[users]]
                  name = "franta"
                  mail = "{{ .GLAUTH_FRANTA_EMAIL }}"
                  givenname = "Franta"
                  sn = "Bartik"
                  uidnumber = 5001
                  primarygroup = 6502
                  othergroups = [ 6501 ]
                  passbcrypt = "{{ .GLAUTH_FRANTA_PASSWORD_BCRYPT }}"
                [[users]]
                  name = "cara"
                  mail = "{{ .GLAUTH_CARA_EMAIL }}"
                  givenname = "Cara"
                  sn = "Kardas"
                  uidnumber = 5002
                  primarygroup = 6502
                  othergroups = [ 6501 ]
                  passbcrypt = "{{ .GLAUTH_CARA_PASSWORD_BCRYPT }}"
        dataFrom:
        - extract:
            key: /glauth
    controllers:
      glauth:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/glauth/glauth
              tag: v2.5.4@sha256:6d448805cf54fc2ca3bca2b87f89dffe571a354a69a667b5a910111be3cf430e
            command: ["/app/glauth", "-c", "/config"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 5555
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: *app
        ipFamilyPolicy: RequireDualStack
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: 389
            protocol: TCP
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        type: secret
        name: glauth-secret
        globalMounts:
          - path: /config/groups.toml
            subPath: groups.toml
            readOnly: true
          - path: /config/server.toml
            subPath: server.toml
            readOnly: true
          - path: /config/users.toml
            subPath: users.toml
            readOnly: true
