---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: miscellaneous-rules
spec:
  groups:
    - name: dockerhub
      rules:
        - alert: BootstrapRateLimitRisk
          annotations:
            summary: Kubernetes cluster at risk of being rate limited by dockerhub on bootstrap
          expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          for: 15m
          labels:
            severity: critical
    - name: oom
      rules:
        - alert: OOMKilled
          annotations:
            summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
          expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          labels:
            severity: critical
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nut-exporter
spec:
  groups:
    - name: nut-exporter.rules
      rules:
        - alert: NutExporterAbsent
          annotations:
            description: NUT exporter has disappeared from Prometheus target discovery.
            summary: NUT Exporter is down.
          expr: |
            absent(up{job=~".*nut-exporter.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: UpsOnBattery
          annotations:
            description: UPS {{ $labels.instance }} has lost power and is running on battery.
            summary: UPS is running on battery.
          expr: network_ups_tools_ups_status{flag="OB"} == 1
          for: 10s
          labels:
            severity: warning
        - alert: UpsLowRuntime
          annotations:
            description: UPS {{ $labels.instance }} battery is low and the system is getting
              ready to shutdown.
            summary: UPS battery is low.
          expr: |
            (
              network_ups_tools_ups_status{flag="OB"} == 1
            and
              network_ups_tools_battery_runtime < 600
            )
          for: 1m
          labels:
            severity: critical
        - alert: UpsLowBattery
          expr: network_ups_tools_battery_charge < 50
          labels:
            severity: warning
          annotations:
            description: UPS {{ $labels.instance }} battery charge is {{ $value }} which is below 50%.
            summary: UPS battery low
        - alert: UpsBatteryReplace
          annotations:
            description: UPS {{ $labels.ups }} battery needs to be replaced.
            summary: Replace UPS battery.
          expr: |
            network_ups_tools_ups_status{flag="RB"} == 1
          for: 10s
          labels:
            severity: warning
