---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name transmission-music-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RED_API_KEY: "{{ .RED_API_KEY }}"
        OPS_API_KEY: "{{ .OPS_API_KEY }}"
        WRTAG_API_KEY: "{{ .WRTAG_API_KEY }}"
        NEMOROSA_API_KEY: "{{ .NEMOROSA_API_KEY }}"
  dataFrom:
  - extract:
      key: /varroa
  - extract:
      key: /wrtag
  - extract:
      key: /nemorosa
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name nemorosa-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        config.yml: |
          global:
            # Global settings
            loglevel: debug
            no_download: false
            exclude_mp3: true
            check_trackers:
              - "flacsfor.me"
              - "home.opsfet.ch"
            check_music_only: true
            auto_start_torrents: true

          linking:
            # File linking configuration
            enable_linking: true
            link_dirs:
              - "/music/downloads/nemorosa"
            link_type: "hardlink"

          server:
            # Web server settings
            host: null # Means 0.0.0.0 and ::
            port: 8256
            api_key: "{{ .NEMOROSA_API_KEY }}"
            search_cadence: "1 day"
            cleanup_cadence: "1 day"

          downloader:
            # Torrent client settings
            - type: "transmission"
              url: "http://transmission-music.media.svc.cluster.local:9091/transmission/rpc"
              torrents_dir: "/config/torrents"
              label: "nemorosa"

          target_site:
            # Target tracker settings
            - server: "https://redacted.sh"
              api_key: "{{ .RED_API_KEY }}"
            - server: "https://orpheus.network"
              api_key: "{{ .OPS_API_KEY }}"
  dataFrom:
    - extract:
        key: /nemorosa
    - extract:
        key: /varroa
