---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app transmission-music
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph-external
    - name: volsync
      namespace: storage
  values:
    controllers:
      transmission:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/frantathefranta/transmission
              tag: 4.1.1@sha256:c982dd821c0539b2a36d000e129bfa5aa02521fa5b078120bc2a9ec64704de06
            env:
              TZ: America/Detroit
              TRANSMISSION__BLOCKLIST_URL: "https://mirror.codebucket.de/transmission/blocklist.p2p.gz"
              TRANSMISSION__DOWNLOAD_DIR: "/music/downloads"
              TRANSMISSION__INCOMPLETE_DIR_ENABLED: false
              TRANSMISSION__RPC_BIND_ADDRESS: "::"
              TRANSMISSION__RPC_PORT: &port 9091
              TRANSMISSION__RPC_WHITELIST: "10.*.*.*"
              TRANSMISSION__RPC_WHITELIST_ENABLED: false
              TRANSMISSION__RPC_HOST_WHITELIST_ENABLED: false
              TRANSMISSION__PEER_PORT: &peerport 51414
              TRANSMISSION__RATIO_LIMIT_ENABLED: false
              TRANSMISSION__UTP_ENABLED: false
              TRANSMISSION__UMASK: 7
              TRANSMISSION__MESSAGE_LEVEL: 3
              TRANSMISSION__WATCH_DIR_ENABLED: true
              TRANSMISSION__WATCH_DIR: "/music/downloads/watch"
              TRANSMISSION__WATCH_FORCE_GENERIC: true
              TRANSMISSION__SCRIPT_TORRENT_DONE_ENABLED: true
              TRANSMISSION__SCRIPT_TORRENT_DONE_FILENAME: /scripts/transmission-complete.sh
            envFrom:
              - secretRef:
                  name: transmission-music-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /transmission/web/
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /transmission/web/
                    port: *port
                  failureThreshold: 50
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
          nemorosa:
            image:
              repository: ghcr.io/kyokomiki/nemorosa
              tag: 0.5.0@sha256:98c9044c5b26844d6cff4b5ab7899cc127b051c38c10746b9d729b20679f0600
            args:
              - --server
            env:
              TZ: America/Detroit
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1003
        fsGroup: 1003
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: transmission
        type: LoadBalancer
        ipFamilyPolicy: RequireDualStack
        annotations:
          lbipam.cilium.io/ips: 10.33.40.65,${CLUSTER_LBA_V6_PREFIX}:65
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *peerport
            protocol: TCP
      nemorosa:
        controller: transmission
        ipFamilyPolicy: RequireDualStack
        ports:
          http:
            port: &nemorosaPort 80

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.franta.us"
          - tm.franta.us
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
      nemorosa:
        hostnames:
          - nemorosa.franta.us
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: nemorosa
                port: *nemorosaPort
    persistence:
      config:
        existingClaim: *app
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: ${NAS_IP}
        path: /emc1/music
        globalMounts:
          - path: /music
      nemorosa:
        existingClaim: nemorosa
        advancedMounts:
          transmission:
            nemorosa:
              - path: /app/data
      nemorosa-config-file:
        type: secret
        name: nemorosa-secret
        advancedMounts:
          transmission:
            nemorosa:
              - path: /app/data/nemorosa/config.yml
                subPath: config.yml
                readOnly: true
      scripts:
        type: configMap
        name: transmission-music-scripts
        defaultMode: 0755
        globalMounts:
          - path: /scripts
