---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "mosquitto-allow-ingress"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
  ingress:
  - fromEntities:
    - "world"
