---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-external
spec:
  chartRef:
    kind: OCIRepository
    name: cloudflare-dns
    namespace: network
  interval: 30m
  values:
    fullnameOverride: *app
    service:
      ipFamilyPolicy: PreferDualStack
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-secret
            key: api-token
    extraArgs:
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=external
    triggerLoopOnEvent: true
    policy: sync
    annotationPrefix: external-dns.alpha.kubernetes.io/
    sources: ["crd", "gateway-httproute"]
    txtPrefix: k8s.
    txtOwnerId: talos-maxi
    domainFilters:
      - franta.us
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
