{
 "title": "Anubis",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(anubis_policy_results,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Anubis (on git.franta.us)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests handled",
   "type": "stat",
   "description": "Total number of requests handled on the selected interval",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(anubis_policy_results{service=~\"$instance\"}[$__range]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests allowed",
   "type": "stat",
   "description": "Requests allowed to pass through to the upstream server over the time interval selected",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anubis_proxied_requests_total{service=~\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(anubis_policy_results{service=~\"$instance\", action='ALLOW'}[$__rate_interval]))",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(rate(anubis_policy_results{service=~\"$instance\", action=\"DENY\"}[$__rate_interval]))",
     "legendFormat": "Denied"
    },
    {
     "expr": "sum(rate(anubis_policy_results{service=~\"$instance\", action=\"CHALLENGE\"}[$__rate_interval]))",
     "legendFormat": "Challenged"
    },
    {
     "expr": "sum(rate(anubis_policy_results{service=~\"$instance\"}[1h]))",
     "legendFormat": "1-hour average"
    },
    {
     "expr": "sum(rate(anubis_policy_results{service=~\"$instance\"}[24h]))",
     "legendFormat": "24-hour average"
    }
   ]
  },
  {
   "title": "Verdicts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(anubis_policy_results{service=~\"$instance\"}[$__range]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Challenge results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anubis_challenges_validated{service=~\"$instance\"}[$__range])",
     "legendFormat": "Validated"
    },
    {
     "expr": "increase(anubis_failed_validations{service=~\"$instance\"}[$__range])",
     "legendFormat": "Failed"
    },
    {
     "expr": "increase(anubis_challenges_issued{service=~\"$instance\"}[$__range]) - increase(anubis_challenges_validated{service=~\"$instance\"}[$__range])",
     "legendFormat": "No response"
    }
   ]
  }
 ]
}