{
 "title": "BGP",
 "description": "The BGP protocol insights.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(bird_protocol_up,instance)"
    }
   },
   {
    "name": "version",
    "label": "IPv",
    "query": {
     "query": "label_values(bird_protocol_up,ip_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BGP Status",
   "type": "stat",
   "description": "BGP establishment status",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_up{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Bird Socket",
   "type": "stat",
   "description": "Result of querying the bird socket",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_socket_query_success{instance=\"$instance:9324\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the BGP protocol.",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_uptime{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "preferred routes",
   "type": "stat",
   "description": "Number of preferred routes.",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "iBGP % of routes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(bird_protocol_prefix_preferred_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\", name=~\"iBGP.*_v$version\"})\n/ \nsum(bird_protocol_prefix_preferred_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\", name!~\"iBGP.*_v$version\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "preferred routes",
   "type": "timeseries",
   "description": "Number of preferred routes.",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Route Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "BGP Import",
   "type": "timeseries",
   "description": "The rate of imported routes via the BGP protocol.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_prefix_import_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "BGP Export",
   "type": "timeseries",
   "description": "The rate of exported routes via the BGP protocol.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_prefix_export_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "BGP filtered",
   "type": "timeseries",
   "description": "The rate of filtered routes via the BGP protocol.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_prefix_filter_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Update Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Incoming total updates",
   "type": "timeseries",
   "description": "The rate of received updates.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_import_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Accepted incoming updates",
   "type": "timeseries",
   "description": "The rate of incoming accepted updates received.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_import_accept_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rejected incoming updates",
   "type": "timeseries",
   "description": "The rate of incoming rejected updates received.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_import_reject_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Outgoing total updates",
   "type": "timeseries",
   "description": "The rate of sent updates.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_export_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Accepted outgoing updates",
   "type": "timeseries",
   "description": "The rate of outgoing accepted updates received.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_export_accept_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rejected outgoing updates",
   "type": "timeseries",
   "description": "The rate of outgoing rejected updates received.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_update_export_reject_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Withdraw Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Incoming total withdraws",
   "type": "timeseries",
   "description": "Total received withdraws.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_withdraw_import_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Incoming accepted withdraws",
   "type": "timeseries",
   "description": "Incoming accepted withdrawals.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_withdraw_import_accept_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Outgoing total withdraws",
   "type": "timeseries",
   "description": "Total send withdraws.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_withdraw_export_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Outgoing accepted withdraws",
   "type": "timeseries",
   "description": "Accepted sent withdrawals.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bird_protocol_changes_withdraw_import_accept_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$version\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}