{
 "title": "BGP Core",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ip_version",
    "label": "Protocol",
    "query": {
     "query": "label_values(bird_protocol_up,ip_version)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(bird_protocol_up{instance!~\"\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "## AS4242421033 BGP Status\n- Contact dn42 [at] franta.us or `frantathefranta` on #dn42 (or see https://franta.us/dn42)"
   }
  },
  {
   "title": "Host Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  1 * (bird_protocol_up{instance=\"$instance\", instance=\"molybdenum.*\"} * 0 + 1) or\n  2 * (bird_protocol_up{instance=\"$instance\", instance=\"nix-vultr.*\"} * 0 + 1) or\n  3 * (bird_protocol_up{instance=\"$instance\", instance=\"nix-hetzner.*\"} * 0 + 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Sessions 🌍",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frr_bgp_peers_count_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instance Peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bird_protocol_up{ip_version=\"$ip_version\", instance=\"$instance:9324\", state=\"Established\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Groups",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_peer_groups_count_total{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bird_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Routing Table Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frr_bgp_rib_memory_bytes{afi=\"$afi\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Routes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_prefix_export_count{proto=\"Kernel\", ip_version=\"$ip_version\", instance=\"$instance:9324\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer State History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bird_protocol_up{instance=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\", ip_version=\"$ip_version\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Peer Update Rate",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(bird_protocol_changes_update_import_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$ip_version\", name=~\".*bgp.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Session Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "bird_protocol_up{ip_version=\"$ip_version\",instance=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\"}",
     "legendFormat": "State"
    },
    {
     "expr": "bird_protocol_prefix_import_count{ip_version=\"$ip_version\", instance=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "bird_protocol_prefix_export_count{ip_version=\"$ip_version\", instance=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bird_protocol_prefix_preferred_count{ip_version=\"$ip_version\", instance=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "bird_protocol_uptime{instance=\"$ip_version\", ip_version=\"$instance:9324\", proto=\"BGP\", name=~\".*bgp.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(bird_protocol_changes_update_import_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$ip_version\", name=~\".*bgp.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "-irate(bird_protocol_changes_update_export_receive_count{proto=\"BGP\", instance=\"$instance:9324\", ip_version=\"$ip_version\", name=~\".*bgp.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "BGP Transit",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{instance=\"$instance:9586\"}[$__rate_interval])*8",
     "legendFormat": "{{interface}} In"
    },
    {
     "expr": "-irate(wireguard_sent_bytes_total{instance=\"$instance:9586\"}[$__rate_interval])*8",
     "legendFormat": "{{interface}} Out"
    }
   ]
  },
  {
   "title": "IGP Ping Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{node=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}