{
 "title": "Autobrr",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autobrr_info",
     "legendFormat": "Autobrr {{version}} - {{revision}}"
    }
   ]
  },
  {
   "title": "Autobrr Releases",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(autobrr_release_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Filters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(autobrr_filter_enabled_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lists",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(autobrr_list_enabled_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feeds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(autobrr_feed_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IRC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(autobrr_irc_enabled_total)", "legendFormat": "Enabled" },
    {
     "expr": "max(autobrr_irc_connected_total)",
     "legendFormat": "Connected"
    },
    {
     "expr": "max(autobrr_irc_enabled_total - autobrr_irc_connected_total)",
     "legendFormat": "Disconnected"
    }
   ]
  },
  {
   "title": "Autobrr Releases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(autobrr_release_filter_rejected_total)",
     "legendFormat": "rejected"
    },
    { "expr": "max(autobrr_release_total)", "legendFormat": "total" },
    {
     "expr": "max(autobrr_release_filtered_total)",
     "legendFormat": "filtered"
    },
    {
     "expr": "max(autobrr_release_push_rejected_total)",
     "legendFormat": "push_rejected"
    },
    {
     "expr": "max(autobrr_release_push_approved_total)",
     "legendFormat": "push_approved"
    },
    {
     "expr": "max(autobrr_release_push_error_total)",
     "legendFormat": "push_error"
    }
   ]
  },
  {
   "title": "Autobrr Last/Next Run RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - autobrr_feed_last_run_timestamp_seconds) by (feed)",
     "legendFormat": "Last - {{feed}}"
    },
    {
     "expr": "max(autobrr_feed_next_run_timestamp_seconds - time()) by (feed)",
     "legendFormat": "Next - {{feed}}"
    }
   ]
  },
  {
   "title": "Autobrr Latest IRC announce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - autobrr_irc_channel_last_announced_timestamp_seconds) by (network, channel)",
     "legendFormat": "{{network}} - {{channel}}"
    }
   ]
  },
  {
   "title": "Autobrr Last Refresh Lists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - autobrr_list_last_refresh_timestamp_seconds) by (list)",
     "legendFormat": "{{list}}"
    }
   ]
  }
 ]
}