---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: garage
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}
  retention:
    keepHourly: 24
    keepDaily: 7
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=ceph-rbd-snapshot}
  copyMethod: ${KOPIUR_COPY_METHOD:=Snapshot}
  mover:
    cache:
      capacity: ${KOPIUR_CACHE_CAPACITY:=4Gi}
      mode: Persistent
      storageClassName: ${KOPIUR_CACHE_STORAGECLASS:=ceph-rbd}
    podSecurityContext:
      runAsUser: ${KOPIUR_MOVER_UID:=568}
      runAsGroup: ${KOPIUR_MOVER_GID:=568}
      fsGroup: ${KOPIUR_MOVER_GID:=568}
  verification:
    deep:
      schedule:
        cron: H 5 1 * *
    quick:
      schedule:
        cron: H 3 * * *
