---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app idrac-fan-control
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  install:
    createNamespace: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      actinium:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app: &idrac-app
            image:
              repository: ghcr.io/tigerblue77/dell_idrac_fan_controller
              tag: v1.12@sha256:d308284e30302d4b8dc8ad2ba15e93576db48275339b394ea390f4d86a698d41
            env:
              FAN_SPEED: 15
              CPU_TEMPERATURE_THRESHOLD: 85
              CHECK_INTERAL: 60 # default
              DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: true
              IDRAC_HOST: bmc-actinium.infra.franta.us
            envFrom:
            - secretRef:
                name: idrac-fan-control-secret
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                cpu: 50m
                memory: 100Mi
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                    - actinium
      thorium:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            <<: *idrac-app
            env:
              FAN_SPEED: 15
              CPU_TEMPERATURE_THRESHOLD: 85
              CHECK_INTERAL: 60 # default
              DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: true
              IDRAC_HOST: bmc-thorium.infra.franta.us
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                    - thorium
      protactinium:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            <<: *idrac-app
            env:
              FAN_SPEED: 15
              CPU_TEMPERATURE_THRESHOLD: 85
              CHECK_INTERAL: 60 # default
              DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: true
              IDRAC_HOST: bmc-protactinium.infra.franta.us
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: NotIn
                    values:
                    - protactinium
