---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name go2rtc-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        go2rtc.yaml: |-
          log:
            streams: error # Prevent log spam
          api:
            listen: :80
            origin: "*"
          rtsp:
            listen: :554
          webrtc:
            listen: :8555
            candidates:
              - 10.33.40.67:8555
              - stun:8555
            ice_servers:
              - urls:
                  - stun:stun.cloudflare.com:3478
          streams:
            sunroom:
              - "rtmp://10.0.50.201/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={{ .REOLINK_PASSWORD }}"
              - "rtmp://10.0.50.201/bcs/channel0_ext.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
              - "rtmp://10.0.50.201/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
            yard:
              - "rtmp://10.0.50.202/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={{ .REOLINK_PASSWORD }}"
              - "rtmp://10.0.50.202/bcs/channel0_ext.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
              - "rtmp://10.0.50.202/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
  dataFrom:
  - extract:
      key: /go2rtc
