---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go2rtc
spec:
  chartRef:
    kind: OCIRepository
    name: go2rtc
  interval: 1h
  values:
    externalSecrets:
      main:
        forceRename: go2rtc-secret
        secretStoreRef:
          name: akeyless-secret-store
          kind: ClusterSecretStore
        refreshInterval: 15m
        target:
          name: go2rtc-secret
          template:
            engineVersion: v2
            data:
              go2rtc.yaml: |-
                log:
                  streams: info
                api:
                  listen: :80
                  origin: "*"
                rtsp:
                  listen: :554
                webrtc:
                  listen: :8555
                  candidates:
                    - 10.33.40.67:8555
                    - stun:8555
                  ice_servers:
                    - urls:
                        - stun:stun.cloudflare.com:3478
                streams:
                  sunroom:
                    - "rtmp://10.0.50.201/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={{ .REOLINK_PASSWORD }}"
                    - "rtmp://10.0.50.201/bcs/channel0_ext.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
                    - "rtmp://10.0.50.201/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
                  yard:
                    - "rtmp://10.0.50.202/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={{ .REOLINK_PASSWORD }}"
                    - "rtmp://10.0.50.202/bcs/channel0_ext.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
                    - "rtmp://10.0.50.202/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password={{ .REOLINK_PASSWORD }}"
        dataFrom:
        - extract:
            key: /go2rtc
    controllers:
      go2rtc:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/alexxit/go2rtc
              tag: 1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: 80
      streams:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.33.40.67,${CLUSTER_LBA_V6_PREFIX}:67
        externalTrafficPolicy: Local
        ports:
          streams-rtsp:
            port: 554
          streams-webrtc-tcp:
            port: 8555
            protocol: TCP
          streams-webrtc-udp:
            port: 8555
            protocol: UDP
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.franta.us"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      config-file:
        type: secret
        name: go2rtc-secret
        globalMounts:
          - path: /config/go2rtc.yaml
            subPath: go2rtc.yaml
