---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maintainerr
spec:
  chartRef:
    kind: OCIRepository
    name: maintainerr
  interval: 30m
  values:
    controllers:
      maintainerr:
        pod:
          securityContext:
            fsGroup: 1003
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1003
            runAsNonRoot: true
            runAsUser: 568
        containers:
          app:
            image:
              repository: ghcr.io/maintainerr/maintainerr
              tag: 3.27.0@sha256:64160eefe3a98a94fdbf8037b607ed7780a2fd95be233ef112c19e67a9bda638
            env:
              UI_PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &probeSpec
                  httpGet:
                    path: /api/health
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                <<: *probes
                spec:
                  <<: *probeSpec
                  periodSeconds: 10
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: maintainerr
        advancedMounts:
          maintainerr:
            app:
              - path: /opt/data
                subPath: data
    route:
      app:
        hostnames:
          - maintainerr.franta.us
        parentRefs:
          - name: internal
            namespace: kube-system
    service:
      app:
        ports:
          http:
            port: *port
