---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app birdnet
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: birdnet

  dependsOn:
    - name: scrypted
      namespace: home-automation
    - name: rook-ceph-cluster
      namespace: rook-ceph-external
  values:
    externalSecrets:
      main:
        forceRename: birdnet-secret
        secretStoreRef:
          name: akeyless-secret-store
          kind: ClusterSecretStore
        target:
          name: birdnet-secret
          template:
            engineVersion: v2
            data:
              config.yaml: |
                debug: false
                main:
                    name: BirdNET-Go
                    timeas24h: true
                    log:
                        enabled: true
                        path: birdnet.log
                        rotation: daily
                        maxsize: 1048576
                        rotationday: Sunday
                birdnet:
                    sensitivity: 1
                    threshold: 0.8
                    overlap: 1.5
                    longitude: ${HOUSE_LONGITUDE}
                    latitude: ${HOUSE_LATITUDE}
                    threads: 0
                    locale: en
                    rangefilter:
                        model: latest
                        threshold: 0.01
                    modelpath: ""
                    labelpath: ""
                    usexnnpack: false
                realtime:
                    interval: 15
                    processingtime: false
                    audio:
                        source: sysdefault
                        ffmpegpath: ffmpeg
                        soxpath: sox
                        export:
                            debug: false
                            enabled: true
                            path: /clips/
                            type: wav
                            bitrate: 96k
                            retention:
                                debug: false
                                policy: usage
                                maxage: 365d
                        equalizer:
                            enabled: false
                            filters:
                                - type: HighPass
                                  frequency: 100
                                  q: 0
                                  gain: 0
                                  width: 0
                                  passes: 0
                                - type: LowPass
                                  frequency: 15000
                                  q: 0
                                  gain: 0
                                  width: 0
                                  passes: 0
                    dashboard:
                        thumbnails:
                            debug: false
                            summary: true
                            recent: true
                        summarylimit: 30
                    dynamicthreshold:
                        enabled: true
                        debug: false
                        trigger: 0.9
                        min: 0.2
                        validhours: 24
                    log:
                        enabled: true
                        path: birdnet.txt
                    birdweather:
                        enabled: false
                        debug: false
                        id: ""
                        threshold: 0.8
                        locationaccuracy: 500
                    openweather:
                        enabled: false
                        debug: false
                        apikey: ""
                        endpoint: https://api.openweathermap.org/data/2.5/weather
                        interval: 60
                        units: metric
                        language: en
                    privacyfilter:
                        debug: false
                        enabled: true
                        confidence: 0.05
                    dogbarkfilter:
                        debug: false
                        enabled: true
                        confidence: 0.1
                        remember: 5
                        species: []
                    rtsp:
                        transport: tcp
                        urls:
                            - rtsp://scrypted.home-automation.svc.cluster.local:34135/257656a9151ff8d4
                    mqtt:
                        enabled: true
                        broker: tcp://mosquitto:1883
                        topic: birdnet
                    telemetry:
                        enabled: true
                        listen: 0.0.0.0:8090
                    species:
                        threshold: {}
                        actions: {}
                        include: []
                        exclude: []
                webserver:
                    enabled: true
                    port: "8080"
                    log:
                        enabled: false
                        path: webui.log
                        rotation: daily
                        maxsize: 1048576
                        rotationday: "0"
                security:
                    host: "https://birdnet.franta.us"
                    autotls: false
                    redirecttohttps: false
                    allowsubnetbypass:
                        enabled: false
                        subnet: ""
                    allowcloudflarebypass:
                        enabled: false
                        teamdomain: ""
                        audience: ""
                    basicauth:
                        enabled: false
                        password: ""
                        clientid: ""
                        clientsecret: "{{ .BASIC_AUTH_CLIENT_SECRET }}"
                        redirecturi: ""
                        authcodeexp: 10m0s
                        accesstokenexp: 1h0m0s
                    googleauth:
                        enabled: false
                        clientid: ""
                        clientsecret: ""
                        redirecturi: /settings
                        userid: ""
                    githubauth:
                        enabled: false
                        clientid: ""
                        clientsecret: ""
                        redirecturi: /settings
                        userid: ""
                    sessionsecret: ""
                output:
                    file: {}
                    sqlite:
                        enabled: true
                        path: birdnet.db
                    mysql:
                        enabled: false
                        username: birdnet
                        password: secret
                        database: birdnet
                        host: localhost
                        port: "3306"
        dataFrom:
        - extract:
            key: /birdnet
    controllers:
      birdnet:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tphakala/birdnet-go
              tag: v0.6.3@sha256:a705ff35fa01187a05e42f0e14d7f41dc9dd2c713dde9cd2dcd568178eae5d4c
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/detections
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          metrics:
            port: 8090
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.franta.us"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: *app
      clips:
        type: nfs
        server: ${NAS_IP}
        path: /emc1/birdnet
        globalMounts:
          - path: /clips
      config:
        type: secret
        name: birdnet-secret
        globalMounts:
          - path: /etc/birdnet-go/config.yaml
            subPath: config.yaml
            readOnly: true
