---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-anubis-key
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: ${APP}-anubis-key-secret
    creationPolicy: Owner
    template:
      data:
        ED25519_PRIVATE_KEY_HEX: "{{ .anubis_ed25519_private_key_hex }}"
  dataFrom:
    - extract:
        key: /anubis
