---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish Terraform"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["terraform/**"]

jobs:
  publish-terraform:
    name: Publish Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@8a142227998406381655ae2982b49542c6c9201e # master

      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner
        run: |
          echo "LOWERCASE_REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> "${GITHUB_ENV}"

      - name: Generate Tag
        id: generate-tag
        run: |
          echo "tag=ghcr.io/${LOWERCASE_REPO_OWNER}/manifests/terraform:$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Publish OCI Artifact
        run: |
          flux push artifact oci://${{ steps.generate-tag.outputs.tag }} \
              --path="./terraform" \
              --source="$(git config --get remote.origin.url)" \
              --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

      - name: Tag OCI Artifact
        run: |
          flux tag artifact \
              oci://${{ steps.generate-tag.outputs.tag }} \
              --tag main
